import React, { useState } from 'react';
import {
  Filter,
  Calendar,
  MapPin,
  Layers,
  Sprout,
  Download,
  FileSpreadsheet,
  FileText,
  Check,
  X,
  Printer,
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export interface GlobalFilterState {
  dateRange: string;
  state: string;
  lga: string;
  valueChain: string;
  commodity: string;
}

interface AdminGlobalFilterBarProps {
  filters: GlobalFilterState;
  onFilterChange: (filters: GlobalFilterState) => void;
  roleTitle: string;
  departmentTag: string;
  watermarkText: string;
  isStateLocked?: boolean;
  lockedStateName?: string;
}

const NIGERIAN_STATES = [
  'All States',
  'Kano',
  'Kaduna',
  'Benue',
  'Niger',
  'Ogun',
  'Taraba',
  'Plateau',
  'Kebbi',
  'Oyo',
  'Cross River',
  'Sokoto',
  'Jigawa',
  'Borno',
  'Adamawa',
  'Enugu',
  'FCT Abuja',
];

const LGAS_BY_STATE: Record<string, string[]> = {
  Kano: ['All LGAs', 'Dala', 'Fagge', 'Kano Municipal', 'Bichi', 'Kura', 'Wudil', 'Garko'],
  Kaduna: ['All LGAs', 'Zaria', 'Giwa', 'Makarfi', 'Kaduna North', 'Chikun', 'Igabi', 'Birnin Gwari'],
  Benue: ['All LGAs', 'Makurdi', 'Gboko', 'Otukpo', 'Gwer West', 'Vandeikya', 'Katsina-Ala'],
  Niger: ['All LGAs', 'Mokwa', 'Bida', 'Minna', 'Kontagora', 'Suleja', 'Lavun'],
  Ogun: ['All LGAs', 'Abeokuta South', 'Ijebu Ode', 'Obafemi Owode', 'Sagamu', 'Yewa North'],
  Taraba: ['All LGAs', 'Jalingo', 'Wukari', 'Gashaka', 'Sardauna', 'Bali'],
  Plateau: ['All LGAs', 'Jos South', 'Jos North', 'Bokkos', 'Mangu', 'Pankshin'],
};

const VALUE_CHAINS = [
  'All Value Chains',
  'Grains & Cereals',
  'Roots & Tubers',
  'Legumes & Oilseeds',
  'Vegetables & Fruits',
  'Livestock & Poultry',
  'Agricultural Inputs & Machinery',
];

const COMMODITIES = [
  'All Commodities',
  'White Maize',
  'Paddy Rice',
  'Cassava Tubers',
  'Yam Tubers',
  'Soybeans',
  'Sorghum',
  'Sesame Seeds',
  'Cowpea / Beans',
  'Tomatoes',
  'NPK 20-10-10 Fertilizer',
  'Urea 46-0-0',
];

export const AdminGlobalFilterBar: React.FC<AdminGlobalFilterBarProps> = ({
  filters,
  onFilterChange,
  roleTitle,
  departmentTag,
  watermarkText,
  isStateLocked = false,
  lockedStateName,
}) => {
  const { user } = useAuth();
  const [showExportModal, setShowExportModal] = useState<boolean>(false);
  const [exportFormat, setExportFormat] = useState<'pdf' | 'csv' | 'excel'>('pdf');
  const [exportSuccess, setExportSuccess] = useState<string | null>(null);

  const availableLgas =
    filters.state !== 'All States' && LGAS_BY_STATE[filters.state]
      ? LGAS_BY_STATE[filters.state]
      : ['All LGAs'];

  const handleStateChange = (newState: string) => {
    onFilterChange({
      ...filters,
      state: newState,
      lga: 'All LGAs',
    });
  };

  const handleExportDownload = () => {
    // Generate downloadable export payload
    const exportTime = new Date().toLocaleString();
    const exportData = {
      meta: {
        system: 'AgriGov Nigeria National Digital Agriculture Platform',
        department: departmentTag,
        role: roleTitle,
        officer: user?.name || 'Authorized Officer',
        watermark: watermarkText,
        filtersApplied: filters,
        generatedAt: exportTime,
      },
      content: `CONFIDENTIAL GOVERNMENT AUDIT EXPORT\nWatermark: ${watermarkText}\nGenerated by: ${user?.name} (${roleTitle})\nScope: State=${filters.state}, LGA=${filters.lga}, ValueChain=${filters.valueChain}, Commodity=${filters.commodity}\nTimestamp: ${exportTime}`,
    };

    if (exportFormat === 'csv') {
      const csvContent =
        'data:text/csv;charset=utf-8,' +
        encodeURIComponent(
          `"AGRIGOV NIGERIA OFFICIAL EXPORT - ${watermarkText}"\n` +
            `"Department","${departmentTag}"\n` +
            `"Generated By","${user?.name} (${roleTitle})"\n` +
            `"Timestamp","${exportTime}"\n` +
            `"State","${filters.state}"\n` +
            `"LGA","${filters.lga}"\n` +
            `"Value Chain","${filters.valueChain}"\n` +
            `"Commodity","${filters.commodity}"\n\n` +
            `"Metric","Benchmark","Current Reading","Variance","Status"\n` +
            `"Target Production MT","12,500,000","13,200,000","+5.6%","Optimal"\n` +
            `"Input Subsidies Disbursed","₦18.4B","₦17.9B","-2.7%","On Track"\n` +
            `"Registered Farmers","4,850,000","5,120,000","+5.5%","Surpassed"\n` +
            `"BOA Loan Recovery","92.0%","94.8%","+2.8%","Low Risk"`
        );
      const link = document.createElement('a');
      link.setAttribute('href', csvContent);
      link.setAttribute('download', `AgriGov_${departmentTag.replace(/\s+/g, '_')}_Report.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } else {
      // PDF or Excel visual notification
      setExportSuccess(`${exportFormat.toUpperCase()} generated with watermark: "${watermarkText}"`);
    }

    setTimeout(() => {
      setShowExportModal(false);
      setExportSuccess(null);
    }, 2500);
  };

  return (
    <div className="bg-white rounded-2xl border border-[#c1c8c2]/80 p-3.5 sm:p-4 shadow-xs space-y-3">
      {/* Top Filter Bar Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 pb-2.5 border-b border-[#e5e9e6]">
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-[#012d1d]" />
          <span className="font-heading font-bold text-xs sm:text-sm text-[#012d1d]">
            National Governance Data Filters
          </span>
          <span className="text-[10px] font-semibold text-[#525a54] bg-[#f0f4f1] px-2 py-0.5 rounded-md border border-[#d8deda]">
            {departmentTag}
          </span>
        </div>

        <div className="flex items-center gap-2 self-stretch sm:self-auto justify-between sm:justify-end">
          <span className="text-[11px] text-[#717973] font-medium hidden md:inline">
            Active Scope: <strong>{filters.state}</strong> • <strong>{filters.commodity}</strong>
          </span>
          <button
            type="button"
            onClick={() => setShowExportModal(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-[#012d1d] hover:bg-[#1b4332] text-white text-xs font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-[#c1ecd4]" />
            <span>Export Report</span>
          </button>
        </div>
      </div>

      {/* Filter Controls Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2.5">
        {/* Date Range Selector */}
        <div className="space-y-1">
          <label className="text-[10px] font-bold text-[#525a54] uppercase tracking-wider flex items-center gap-1">
            <Calendar className="w-3 h-3 text-[#012d1d]" />
            <span>Timeline</span>
          </label>
          <select
            value={filters.dateRange}
            onChange={(e) => onFilterChange({ ...filters, dateRange: e.target.value })}
            className="w-full text-xs font-semibold py-1.5 px-2.5 bg-[#f8faf8] border border-[#d8deda] rounded-xl text-[#012d1d] focus:outline-none focus:border-[#012d1d] focus:ring-1 focus:ring-[#012d1d]"
          >
            <option value="last_7_days">Last 7 Days</option>
            <option value="last_30_days">Last 30 Days</option>
            <option value="current_quarter">Current Quarter (Q3 2026)</option>
            <option value="year_to_date">Year-to-Date (2026)</option>
            <option value="natip_cycle">NATIP 5-Yr Policy Cycle</option>
          </select>
        </div>

        {/* State Selector */}
        <div className="space-y-1">
          <label className="text-[10px] font-bold text-[#525a54] uppercase tracking-wider flex items-center gap-1">
            <MapPin className="w-3 h-3 text-[#012d1d]" />
            <span>State</span>
          </label>
          {isStateLocked ? (
            <div className="w-full text-xs font-bold py-1.5 px-2.5 bg-[#e9ece9] border border-[#d8deda] rounded-xl text-[#012d1d] flex items-center justify-between">
              <span>{lockedStateName || filters.state}</span>
              <span className="text-[9px] bg-[#012d1d] text-white px-1.5 py-0.2 rounded font-mono">
                LOCKED
              </span>
            </div>
          ) : (
            <select
              value={filters.state}
              onChange={(e) => handleStateChange(e.target.value)}
              className="w-full text-xs font-semibold py-1.5 px-2.5 bg-[#f8faf8] border border-[#d8deda] rounded-xl text-[#012d1d] focus:outline-none focus:border-[#012d1d] focus:ring-1 focus:ring-[#012d1d]"
            >
              {NIGERIAN_STATES.map((st) => (
                <option key={st} value={st}>
                  {st}
                </option>
              ))}
            </select>
          )}
        </div>

        {/* LGA Selector */}
        <div className="space-y-1">
          <label className="text-[10px] font-bold text-[#525a54] uppercase tracking-wider flex items-center gap-1">
            <MapPin className="w-3 h-3 text-[#012d1d]" />
            <span>LGA / District</span>
          </label>
          <select
            value={filters.lga}
            onChange={(e) => onFilterChange({ ...filters, lga: e.target.value })}
            className="w-full text-xs font-semibold py-1.5 px-2.5 bg-[#f8faf8] border border-[#d8deda] rounded-xl text-[#012d1d] focus:outline-none focus:border-[#012d1d] focus:ring-1 focus:ring-[#012d1d]"
          >
            {availableLgas.map((lg) => (
              <option key={lg} value={lg}>
                {lg}
              </option>
            ))}
          </select>
        </div>

        {/* Value Chain */}
        <div className="space-y-1">
          <label className="text-[10px] font-bold text-[#525a54] uppercase tracking-wider flex items-center gap-1">
            <Layers className="w-3 h-3 text-[#012d1d]" />
            <span>Value Chain</span>
          </label>
          <select
            value={filters.valueChain}
            onChange={(e) => onFilterChange({ ...filters, valueChain: e.target.value })}
            className="w-full text-xs font-semibold py-1.5 px-2.5 bg-[#f8faf8] border border-[#d8deda] rounded-xl text-[#012d1d] focus:outline-none focus:border-[#012d1d] focus:ring-1 focus:ring-[#012d1d]"
          >
            {VALUE_CHAINS.map((vc) => (
              <option key={vc} value={vc}>
                {vc}
              </option>
            ))}
          </select>
        </div>

        {/* Commodity */}
        <div className="space-y-1 col-span-2 sm:col-span-1">
          <label className="text-[10px] font-bold text-[#525a54] uppercase tracking-wider flex items-center gap-1">
            <Sprout className="w-3 h-3 text-[#012d1d]" />
            <span>Commodity</span>
          </label>
          <select
            value={filters.commodity}
            onChange={(e) => onFilterChange({ ...filters, commodity: e.target.value })}
            className="w-full text-xs font-semibold py-1.5 px-2.5 bg-[#f8faf8] border border-[#d8deda] rounded-xl text-[#012d1d] focus:outline-none focus:border-[#012d1d] focus:ring-1 focus:ring-[#012d1d]"
          >
            {COMMODITIES.map((cm) => (
              <option key={cm} value={cm}>
                {cm}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Export Modal with Role-based Watermark */}
      {showExportModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-5 sm:p-6 space-y-4 shadow-2xl border border-[#c1c8c2]">
            <div className="flex justify-between items-center pb-2 border-b border-[#e5e9e6]">
              <div className="flex items-center gap-2">
                <Download className="w-5 h-5 text-[#012d1d]" />
                <h3 className="font-heading font-bold text-base text-[#012d1d]">
                  Generate Official Governance Export
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setShowExportModal(false)}
                className="w-7 h-7 rounded-full flex items-center justify-center hover:bg-[#f0f4f1] text-[#717973]"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Watermark Notice */}
            <div className="p-3 bg-[#f8faf8] rounded-xl border border-[#d8deda] space-y-1.5">
              <div className="flex items-center justify-between text-[11px] font-bold text-[#012d1d]">
                <span>Role Security Watermark:</span>
                <span className="px-2 py-0.5 bg-[#012d1d] text-[#c1ecd4] rounded-md text-[10px] font-mono">
                  AUTHENTICATED
                </span>
              </div>
              <div className="p-2 bg-white rounded-lg border border-[#e2e8e4] text-center font-mono text-xs font-bold text-[#b45309] tracking-wider uppercase select-none">
                {watermarkText}
              </div>
              <p className="text-[10px] text-[#717973]">
                Exports include dynamic security fingerprints, official officer credentials, and cryptographic hash verification.
              </p>
            </div>

            {/* Format Selection */}
            <div className="space-y-2">
              <label className="text-xs font-bold text-[#012d1d]">Select Format</label>
              <div className="grid grid-cols-3 gap-2">
                <button
                  type="button"
                  onClick={() => setExportFormat('pdf')}
                  className={`p-3 rounded-xl border flex flex-col items-center gap-1 text-xs font-bold cursor-pointer transition-all ${
                    exportFormat === 'pdf'
                      ? 'border-[#012d1d] bg-[#f2f7f4] text-[#012d1d] ring-1 ring-[#012d1d]'
                      : 'border-[#d8deda] hover:bg-[#f8faf8] text-[#525a54]'
                  }`}
                >
                  <FileText className="w-5 h-5 text-[#ba1a1a]" />
                  <span>PDF Document</span>
                </button>

                <button
                  type="button"
                  onClick={() => setExportFormat('csv')}
                  className={`p-3 rounded-xl border flex flex-col items-center gap-1 text-xs font-bold cursor-pointer transition-all ${
                    exportFormat === 'csv'
                      ? 'border-[#012d1d] bg-[#f2f7f4] text-[#012d1d] ring-1 ring-[#012d1d]'
                      : 'border-[#d8deda] hover:bg-[#f8faf8] text-[#525a54]'
                  }`}
                >
                  <FileSpreadsheet className="w-5 h-5 text-[#16a34a]" />
                  <span>CSV Raw Data</span>
                </button>

                <button
                  type="button"
                  onClick={() => setExportFormat('excel')}
                  className={`p-3 rounded-xl border flex flex-col items-center gap-1 text-xs font-bold cursor-pointer transition-all ${
                    exportFormat === 'excel'
                      ? 'border-[#012d1d] bg-[#f2f7f4] text-[#012d1d] ring-1 ring-[#012d1d]'
                      : 'border-[#d8deda] hover:bg-[#f8faf8] text-[#525a54]'
                  }`}
                >
                  <Printer className="w-5 h-5 text-[#2563eb]" />
                  <span>Excel (XLSX)</span>
                </button>
              </div>
            </div>

            {/* Success Message */}
            {exportSuccess && (
              <div className="p-3 bg-[#c1ecd4] text-[#002114] rounded-xl text-xs font-bold flex items-center gap-2">
                <Check className="w-4 h-4 text-[#002114]" />
                <span>{exportSuccess}</span>
              </div>
            )}

            {/* Actions */}
            <div className="pt-2 flex items-center gap-2">
              <button
                type="button"
                onClick={() => setShowExportModal(false)}
                className="flex-1 py-2.5 border border-[#d8deda] text-[#525a54] font-bold text-xs rounded-xl hover:bg-[#f8faf8]"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleExportDownload}
                className="flex-1 py-2.5 bg-[#012d1d] hover:bg-[#1b4332] text-white font-bold text-xs rounded-xl flex items-center justify-center gap-1.5 shadow-xs"
              >
                <Download className="w-4 h-4 text-[#c1ecd4]" />
                <span>Confirm & Download</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
export default AdminGlobalFilterBar;
